name: Danecraftserver
version: '${project.version}'
main: com.danecraft.server.danecraftserver.Danecraftserver
api-version: 1.16
commands:
  About:
    description: toggles info about server
    usage: /about
    aliases: a
  cleanInv:
    description: removes garbo blocks from inventory
    usage: /cleanInventory
    aliases: c
  rules:
    description: explains rules
    usage: /rules
    aliases: r
  locateSpawn:
    description: chat message about where spawn is from where you are
    usage: /locateSpawn
    aliases: locateSpawn
  SetCommand:
    description: sets health/hunger of players or self
    usage: /set
    aliases: s

  Kill:
    description: kills player command
    usage: /Kill
    aliases: K
  helpD:
    description: shows player various commands etc
    usage: /helpD
    aliases: h
